### ISSUE TITLE
Head 1 x-axis crashes in head 2 at the beginning of a print

### ISSUE THREAD

**Issue by Melkaz** [foehnsturm/Mark2#1]
At the beginning of a print, head 2 is primed then docked.
Then head 1 x-axis crashes into head 2 when moving for priming.

Do I need to change something in the start gcode ?

**Comment by foehnsturm** [comment]
Check the wiping position in firmware for a safe y value > 23 mm

**Comment by Melkaz** [comment]
I don't have any wiping

**Comment by Melkaz** [comment]
Thanks, testing and will report.

**Comment by Melkaz** [comment]
In : `Advanced/Dual extrusion/Wipe position`
I set a y value of 23.5mm and it works flawlessly.
